### ISSUE TITLE
How to transfer tokens from one user to another user?

### ISSUE THREAD

**Issue by ayu1712** [halls7588/ERC20_Token_Types#3]
This is an amazing repository. The explanation is very lucid. But I got stuck at some place. I'm getting an error when I called a contract method "transferFrom" from user's address to send tokens to another user. I'm keep getting transaction exception. I'm using web3j wallet in android to do all the transactions. I can read balance, get approved limit but can't called transferFrom or mint functions. I keep getting TransactionException without any cause. Please help me resolve this issue.

**Comment by halls7588** [comment]
Use the transfer function. Not the transferFrom.

**Comment by ayu1712** [comment]
Transfer function is for transferring coins from contract owner to one user. What I'm asking is how one user transfer coins to another user. "transfer" function only accept two params (Recipient address and amount).

**Comment by halls7588** [comment]
The Transfer function is for transferring tokens in general. Not just form contract to another wallet. TransferFrom is a method that is part of the ERC20 standard that makes sure you have enough tokens to transfer the amount requested. Literally, use the transfer function to transfer tokens.  That is all you need to do. If you don't believe me, copy the code into remix compiler and test it like I did when I built it and Like I did when you asked me this to test it and make sure it is working. USE THE TRANSFER FUNCTION TO TRANSFER TOKENS. The name of the function is Transfer. It takes an address and an amount. That is all you need to do.

**Comment by ayu1712** [comment]
Thanks man

**Comment by halls7588** [comment]
No problem. happy to help.
